import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Header, Sidebar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-gray-100 w-screen min-h-screen">
          <Sidebar />
          <div className="w-[calc(100vw-16rem)]">
            <Header />
            <div className="p-4 ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
